import type { LessonCatalogOutline, LessonTurnResult } from '../types/lesson'

export const lessonCatalogFixture: LessonCatalogOutline = {
  scope_count: 3,
  page_count: 4,
  block_count: 8,
  scopes: [
    {
      grade: 'G5',
      semester: 'S1',
      unit: 'U3',
      pages: [
        {
          page_uid: 'TB-G5S1U3-P24',
          page: 24,
          page_type: 'dialogue',
          page_intro_cn: '这一页练习点餐和饮料表达。',
        },
      ],
    },
    {
      grade: 'G6',
      semester: 'S1',
      unit: 'U1',
      pages: [
        {
          page_uid: 'TB-G6S1U1-P2',
          page: 2,
          page_type: 'dialogue',
          page_intro_cn: '这一页进入六上第一单元的问路对话。',
        },
      ],
    },
    {
      grade: 'G6',
      semester: 'S2',
      unit: 'Recycle2',
      pages: [
        {
          page_uid: 'TB-G6S2Recycle2-P49',
          page: 49,
          page_type: 'phonics',
          page_intro_cn: '这一页复习告别派对里的语音分类。',
        },
        {
          page_uid: 'TB-G6S2Recycle2-P51',
          page: 51,
          page_type: 'story',
          page_intro_cn: '这一页进入 Recycle 2 的 story time 收尾。',
        },
      ],
    },
  ],
}

export const lessonCatalogSmokeFixture: LessonCatalogOutline = {
  scope_count: 3,
  page_count: 6,
  block_count: 12,
  scopes: [
    {
      grade: 'G5',
      semester: 'S1',
      unit: 'U3',
      pages: [
        {
          page_uid: 'TB-G5S1U3-P24',
          page: 24,
          page_type: 'dialogue',
          page_intro_cn: '这一页练习点餐和饮料表达。',
        },
        {
          page_uid: 'TB-G5S1U3-P25',
          page: 25,
          page_type: 'dialogue',
          page_intro_cn: '这一页我们先看 salad 和 bread 的表达。',
        },
        {
          page_uid: 'TB-G5S1U3-P31',
          page: 31,
          page_type: 'story',
          page_intro_cn: '这一页进入 Unit 3 story 复盘。',
        },
      ],
    },
    ...lessonCatalogFixture.scopes.slice(1),
  ],
}

export const lessonTurnP24StartFixture: LessonTurnResult = {
  page_uid: 'TB-G5S1U3-P24',
  block_uid: 'TB-G5S1U3-P24-D1',
  turn_label: 'page_entry',
  teaching_action: 'page_intro',
  retrieval_mode: 'none',
  teacher_response: '这一页练习点餐和饮料表达。Can you say: What would you like to drink?',
  state: {
    student_id: 'demo-student',
    current_grade: 'G5',
    current_semester: 'S1',
    current_unit: 'U3',
    current_page: 24,
    current_page_uid: 'TB-G5S1U3-P24',
    current_page_type: 'dialogue',
    current_block_uid: 'TB-G5S1U3-P24-D1',
    current_activity_type: 'page_entry',
    awaiting_answer: true,
    last_teacher_question: 'What would you like to drink?',
    hint_level: 0,
    pedagogy_level: 0,
    page_entry_probe_done: true,
    repair_mode: 'none',
    recent_turn_labels: ['page_entry'],
    same_goal_attempt_count: 0,
    last_eval_result: null,
    model_already_given: false,
    branch_active: false,
    branch_reason: null,
    branch_origin_block_uid: null,
    branch_turn_budget: null,
    return_anchor: null,
    return_target: null,
    simplemem_content_session_id: 'lesson-1',
    simplemem_memory_session_id: 'memory-session-p24',
  },
  evaluation: null,
  retrieved_block_uids: [],
  support_entry_uids: [],
  return_anchor: null,
  branch_reason: null,
  debug_signals: {
    live_prompts: {
      enabled: true,
    },
    vector_retrieval: {
      enabled: true,
      hit_modes: ['unit'],
    },
    prompt_memory: {
      enabled: true,
      injected_buckets: ['common_mistakes', 'stable_preferences'],
    },
    semantic_recall: {
      enabled: false,
      recalled_memories: [],
    },
    memory_runtime: {
      student_id: 'demo-student',
      project: 'peptutor-lesson',
      memory_session_id: 'memory-session-p24',
      last_recall_status: 'skipped',
      last_recall_summary: 'This turn did not run learner-memory recall.',
      last_writeback_status: 'skipped',
      last_writeback_summary: 'No learner turn yet; backend writeback has not run.',
      degradation_state: 'idle',
    },
  },
}

export const lessonTurnP24RestartStartFixture: LessonTurnResult = {
  page_uid: 'TB-G5S1U3-P24',
  block_uid: 'TB-G5S1U3-P24-D1',
  turn_label: 'page_entry',
  teaching_action: 'page_intro',
  retrieval_mode: 'none',
  teacher_response: '这一页练习点餐和饮料表达。先说 I am hungry.',
  state: {
    student_id: 'demo-student',
    current_grade: 'G5',
    current_semester: 'S1',
    current_unit: 'U3',
    current_page: 24,
    current_page_uid: 'TB-G5S1U3-P24',
    current_page_type: 'dialogue',
    current_block_uid: 'TB-G5S1U3-P24-D1',
    current_activity_type: 'page_entry',
    awaiting_answer: true,
    last_teacher_question: 'Can you say I am hungry?',
    hint_level: 0,
    pedagogy_level: 0,
    page_entry_probe_done: true,
    repair_mode: 'none',
    recent_turn_labels: ['page_entry'],
    same_goal_attempt_count: 0,
    last_eval_result: null,
    model_already_given: false,
    branch_active: false,
    branch_reason: null,
    branch_origin_block_uid: null,
    branch_turn_budget: null,
    return_anchor: null,
    return_target: null,
    simplemem_content_session_id: 'lesson-24',
    simplemem_memory_session_id: 'memory-session-p24-restart',
  },
  evaluation: null,
  retrieved_block_uids: [],
  support_entry_uids: [],
  return_anchor: null,
  branch_reason: null,
}

export const lessonTurnP24AnswerFixture: LessonTurnResult = {
  page_uid: 'TB-G5S1U3-P24',
  block_uid: 'TB-G5S1U3-P24-D2',
  turn_label: 'answer_question',
  teaching_action: 'confirm',
  retrieval_mode: 'none',
  teacher_response: '对了。我们继续：Now say one full drink sentence.',
  state: {
    student_id: 'demo-student',
    current_grade: 'G5',
    current_semester: 'S1',
    current_unit: 'U3',
    current_page: 24,
    current_page_uid: 'TB-G5S1U3-P24',
    current_page_type: 'dialogue',
    current_block_uid: 'TB-G5S1U3-P24-D2',
    current_activity_type: 'teaching',
    awaiting_answer: true,
    last_teacher_question: 'Now say one full drink sentence.',
    hint_level: 0,
    pedagogy_level: 0,
    page_entry_probe_done: true,
    repair_mode: 'none',
    recent_turn_labels: ['page_entry', 'answer_question'],
    same_goal_attempt_count: 0,
    last_eval_result: 'correct',
    model_already_given: false,
    branch_active: false,
    branch_reason: null,
    branch_origin_block_uid: null,
    branch_turn_budget: null,
    return_anchor: null,
    return_target: null,
    simplemem_content_session_id: 'lesson-1',
    simplemem_memory_session_id: 'memory-session-p24',
  },
  evaluation: 'correct',
  retrieved_block_uids: [],
  support_entry_uids: [],
  return_anchor: null,
  branch_reason: null,
  debug_signals: {
    live_prompts: {
      enabled: true,
    },
    vector_retrieval: {
      enabled: true,
      hit_modes: ['branch'],
    },
    prompt_memory: {
      enabled: true,
      injected_buckets: ['common_mistakes', 'preferences', 'stable_preferences'],
    },
    semantic_recall: {
      enabled: true,
      recalled_memories: ['Learner gets shy when asked to answer aloud.'],
    },
    memory_runtime: {
      student_id: 'demo-student',
      project: 'peptutor-lesson',
      memory_session_id: 'memory-session-p24',
      last_recall_status: 'success',
      last_recall_summary: 'Injected buckets: common_mistakes / preferences / stable_preferences. Semantic hits: 1. Prompt summary available.',
      last_writeback_status: 'success',
      last_writeback_summary: 'Recorded learner turn in backend memory.',
      degradation_state: 'healthy',
    },
  },
}

export const lessonTurnP25StartFixture: LessonTurnResult = {
  page_uid: 'TB-G5S1U3-P25',
  block_uid: 'TB-G5S1U3-P25-D1',
  turn_label: 'page_entry',
  teaching_action: 'page_intro',
  retrieval_mode: 'none',
  teacher_response: '这一页我们先看 salad 和 bread 的表达。',
  state: {
    student_id: 'demo-student',
    current_grade: 'G5',
    current_semester: 'S1',
    current_unit: 'U3',
    current_page: 25,
    current_page_uid: 'TB-G5S1U3-P25',
    current_page_type: 'dialogue',
    current_block_uid: 'TB-G5S1U3-P25-D1',
    current_activity_type: 'page_entry',
    awaiting_answer: true,
    last_teacher_question: 'What food can you see?',
    hint_level: 0,
    pedagogy_level: 0,
    page_entry_probe_done: true,
    repair_mode: 'none',
    recent_turn_labels: ['page_entry'],
    same_goal_attempt_count: 0,
    last_eval_result: null,
    model_already_given: false,
    branch_active: false,
    branch_reason: null,
    branch_origin_block_uid: null,
    branch_turn_budget: null,
    return_anchor: null,
    return_target: null,
    simplemem_content_session_id: 'lesson-25',
    simplemem_memory_session_id: 'memory-session-p25',
  },
  evaluation: null,
  retrieved_block_uids: [],
  support_entry_uids: [],
  return_anchor: null,
  branch_reason: null,
}

export const lessonTurnP31StartFixture: LessonTurnResult = {
  page_uid: 'TB-G5S1U3-P31',
  block_uid: 'TB-G5S1U3-P31-D1',
  turn_label: 'page_entry',
  teaching_action: 'page_intro',
  retrieval_mode: 'none',
  teacher_response: '这一页进入 Unit 3 story 复盘。先说说你看到了什么。',
  state: {
    student_id: 'demo-student',
    current_grade: 'G5',
    current_semester: 'S1',
    current_unit: 'U3',
    current_page: 31,
    current_page_uid: 'TB-G5S1U3-P31',
    current_page_type: 'story',
    current_block_uid: 'TB-G5S1U3-P31-D1',
    current_activity_type: 'page_entry',
    awaiting_answer: true,
    last_teacher_question: 'What can you see in the story?',
    hint_level: 0,
    pedagogy_level: 0,
    page_entry_probe_done: true,
    repair_mode: 'none',
    recent_turn_labels: ['page_entry'],
    same_goal_attempt_count: 0,
    last_eval_result: null,
    model_already_given: false,
    branch_active: false,
    branch_reason: null,
    branch_origin_block_uid: null,
    branch_turn_budget: null,
    return_anchor: null,
    return_target: null,
    simplemem_content_session_id: 'lesson-31',
    simplemem_memory_session_id: 'memory-session-p31',
  },
  evaluation: null,
  retrieved_block_uids: [],
  support_entry_uids: [],
  return_anchor: null,
  branch_reason: null,
}

export function cloneLessonFixture<T>(value: T): T {
  return structuredClone(value)
}

export function lessonJsonResponse(payload: unknown, init: ResponseInit = {}) {
  return new Response(JSON.stringify(payload), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
      ...init.headers,
    },
    ...init,
  })
}
